
CREATE DATABASE moradia;

\c moradia;

CREATE TABLE bairros (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(2) NOT NULL
);

CREATE TABLE ocorrencias (
    id SERIAL PRIMARY KEY,
    bairro_id INTEGER NOT NULL,
    descricao TEXT NOT NULL,
    data_ocorrencia TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bairro_id) REFERENCES bairros(id)
);

INSERT INTO bairros (nome, cidade, estado) VALUES
('Jardins', 'São Paulo', 'SP'),
('Copacabana', 'Rio de Janeiro', 'RJ'),
('Ipanema', 'Rio de Janeiro', 'RJ'),
('Lourdes', 'Belo Horizonte', 'MG'),
('Pinheiros', 'São Paulo', 'SP'),
('Leblon', 'Rio de Janeiro', 'RJ'),
('Vila Madalena', 'São Paulo', 'SP'),
('Barra da Tijuca', 'Rio de Janeiro', 'RJ'),
('Moema', 'São Paulo', 'SP'),
('Savassi', 'Belo Horizonte', 'MG'),
('Boa Viagem', 'Recife', 'PE'),
('Centro', 'Curitiba', 'PR'),
('Batel', 'Curitiba', 'PR'),
('Asa Sul', 'Brasília', 'DF'),
('Asa Norte', 'Brasília', 'DF'),
('Setor Sudoeste', 'Brasília', 'DF'),
('Praia do Canto', 'Vitória', 'ES'),
('Jardim Camburi', 'Vitória', 'ES'),
('Centro', 'Florianópolis', 'SC'),
('Trindade', 'Florianópolis', 'SC'),
('Lagoa da Conceição', 'Florianópolis', 'SC'),
('Centro', 'Porto Alegre', 'RS'),
('Moinhos de Vento', 'Porto Alegre', 'RS'),
('Petrópolis', 'Porto Alegre', 'RS'),
('Centro', 'Salvador', 'BA'),
('Barra', 'Salvador', 'BA'),
('Rio Vermelho', 'Salvador', 'BA'),
('Centro', 'Fortaleza', 'CE'),
('Meireles', 'Fortaleza', 'CE'),
('Aldeota', 'Fortaleza', 'CE'),
('Centro', 'Manaus', 'AM'),
('Adrianópolis', 'Manaus', 'AM'),
('Ponta Negra', 'Manaus', 'AM'),
('Centro', 'Belém', 'PA'),
('Nazaré', 'Belém', 'PA'),
('Umarizal', 'Belém', 'PA'),
('Centro', 'Goiânia', 'GO'),
('Setor Bueno', 'Goiânia', 'GO'),
('Setor Marista', 'Goiânia', 'GO'),
('Centro', 'Campo Grande', 'MS'),
('Jardim dos Estados', 'Campo Grande', 'MS'),
('Vila Planalto', 'Campo Grande', 'MS'),
('Centro', 'João Pessoa', 'PB'),
('Tambaú', 'João Pessoa', 'PB'),
('Cabo Branco', 'João Pessoa', 'PB');

INSERT INTO ocorrencias (bairro_id, descricao) VALUES
(1, 'Aumento de assaltos na região'),
(2, 'Melhoria na iluminação pública'),
(3, 'Protesto contra a violência'),
(4, 'Reunião comunitária sobre segurança'),
(5, 'Aumento de furtos em veículos'),
(6, 'Campanha de conscientização sobre segurança'),
(7, 'Aumento de casos de vandalismo'),
(8, 'Problemas com coleta de lixo'),
(9, 'Reclamação sobre barulho excessivo'),
(10, 'Solicitação de poda de árvores'),
(11, 'Denúncia de ocupação irregular'),
(12, 'Campanha de vacinação comunitária'),
(13, 'Reclamação sobre buracos nas ruas'),
(14, 'Solicitação de instalação de lombadas'),
(15, 'Denúncia de descarte irregular de lixo'),
(16, 'Reclamação sobre falta de iluminação pública'),
(17, 'Solicitação de melhorias no transporte público'),
(18, 'Campanha de doação de alimentos'),
(19, 'Denúncia de poluição sonora'),
(20, 'Reclamação sobre falta de segurança'),
(21, 'Solicitação de instalação de câmeras de segurança'),
(22, 'Denúncia de maus-tratos a animais'),
(23, 'Reclamação sobre enchentes na região'),
(24, 'Solicitação de melhorias em áreas de lazer'),
(25, 'Denúncia de comércio irregular'),
(26, 'Reclamação sobre trânsito intenso'),
(27, 'Solicitação de limpeza de terrenos baldios');